### ISSUE TITLE
Undefined Var

### ISSUE THREAD

**Issue by protometa** [holmberd/js-rbo#1]
When running the example:

    const RBO = require('rbo')
    const rbo = new RBO(0.8)
    const comparison = rbo.calculate(['a', 'b', 'c', 'd', 'e'], ['b', 'a', 'g', 'h', 'e', 'k', 'l', 'c'])

I get the following error:

    /node_modules/rbo/rbo.js:87
      if (s.shortDepth != -1){
      ^

    ReferenceError: s is not defined
        at RBO.update (/Users/lukenimtz/src/gummicube/gp-data-analysis/node_modules/rbo/rbo.js:87:2)
        at RBO.calculate (/Users/lukenimtz/src/gummicube/gp-data-analysis/node_modules/rbo/rbo.js:51:8)
        at Object.<anonymous> (/Users/lukenimtz/src/gummicube/gp-data-analysis/analyze.js:12:24)
        at Module._compile (module.js:624:30)
        at Object.Module._extensions..js (module.js:635:10)
        at Module.load (module.js:545:32)
        at tryModuleLoad (module.js:508:12)
        at Function.Module._load (module.js:500:3)
        at Function.Module.runMain (module.js:665:10)
        at startup (bootstrap_node.js:187:16)

**Comment by holmberd** [comment]
@protometa Thanks for opening an issue and @konsumer for providing the pull request.
